package playlist.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Bin;
  private ConceptPresentation props_Color;
  private ConceptPresentation props_ControlPoint;
  private ConceptPresentation props_Playlist;
  private ConceptPresentation props_Song;
  private ConceptPresentation props_SongRef;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Bin:
        if (props_Bin == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("bin");
          cpb.rawPresentation("Bin");
          props_Bin = cpb.create();
        }
        return props_Bin;
      case LanguageConceptSwitch.Color:
        if (props_Color == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("color");
          cpb.rawPresentation("Color");
          props_Color = cpb.create();
        }
        return props_Color;
      case LanguageConceptSwitch.ControlPoint:
        if (props_ControlPoint == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("control point");
          cpb.rawPresentation("cp");
          props_ControlPoint = cpb.create();
        }
        return props_ControlPoint;
      case LanguageConceptSwitch.Playlist:
        if (props_Playlist == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("playlist");
          cpb.presentationByName();
          props_Playlist = cpb.create();
        }
        return props_Playlist;
      case LanguageConceptSwitch.Song:
        if (props_Song == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("song");
          cpb.presentationByName();
          props_Song = cpb.create();
        }
        return props_Song;
      case LanguageConceptSwitch.SongRef:
        if (props_SongRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("song reference");
          cpb.presentationByReference(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x54d1a88cacfa024eL, 0x54d1a88cacfa024fL, "target", "", "");
          props_SongRef = cpb.create();
        }
        return props_SongRef;
    }
    return null;
  }
}
