package playlist.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptBin = createDescriptorForBin();
  /*package*/ final ConceptDescriptor myConceptColor = createDescriptorForColor();
  /*package*/ final ConceptDescriptor myConceptControlPoint = createDescriptorForControlPoint();
  /*package*/ final ConceptDescriptor myConceptPlaylist = createDescriptorForPlaylist();
  /*package*/ final ConceptDescriptor myConceptSong = createDescriptorForSong();
  /*package*/ final ConceptDescriptor myConceptSongRef = createDescriptorForSongRef();
  /*package*/ final ConceptDescriptor myConceptVisualisation = createDescriptorForVisualisation();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBin, myConceptColor, myConceptControlPoint, myConceptPlaylist, myConceptSong, myConceptSongRef, myConceptVisualisation);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Bin:
        return myConceptBin;
      case LanguageConceptSwitch.Color:
        return myConceptColor;
      case LanguageConceptSwitch.ControlPoint:
        return myConceptControlPoint;
      case LanguageConceptSwitch.Playlist:
        return myConceptPlaylist;
      case LanguageConceptSwitch.Song:
        return myConceptSong;
      case LanguageConceptSwitch.SongRef:
        return myConceptSongRef;
      case LanguageConceptSwitch.Visualisation:
        return myConceptVisualisation;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForBin() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("playlist", "Bin", 0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f15dL);
    b.class_(false, false, false);
    b.origin("r:de050263-7aec-4e3f-a874-7935d74b9031(playlist.structure)/4927355640491471197");
    b.version(2);
    b.property("index", 0x44617bd94982f1f6L).type(PrimitiveTypeId.INTEGER).origin("4927355640491471350").done();
    b.aggregate("color", 0x44617bd94982f1f8L).target(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f15eL).optional(false).ordered(true).multiple(false).origin("4927355640491471352").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("playlist", "Color", 0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f15eL);
    b.class_(false, false, false);
    b.origin("r:de050263-7aec-4e3f-a874-7935d74b9031(playlist.structure)/4927355640491471198");
    b.version(2);
    b.property("r", 0x44617bd94982f15fL).type(PrimitiveTypeId.INTEGER).origin("4927355640491471199").done();
    b.property("g", 0x44617bd94982f161L).type(PrimitiveTypeId.INTEGER).origin("4927355640491471201").done();
    b.property("b", 0x44617bd94982f164L).type(PrimitiveTypeId.INTEGER).origin("4927355640491471204").done();
    b.property("alpha", 0x44617bd94982f168L).type(PrimitiveTypeId.INTEGER).origin("4927355640491471208").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForControlPoint() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("playlist", "ControlPoint", 0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f23aL);
    b.class_(false, false, false);
    b.origin("r:de050263-7aec-4e3f-a874-7935d74b9031(playlist.structure)/4927355640491471418");
    b.version(2);
    b.property("stamp", 0x44617bd94982f23bL).type(PrimitiveTypeId.INTEGER).origin("4927355640491471419").done();
    b.property("brightness", 0x54b5cde27c2af594L).type(PrimitiveTypeId.INTEGER).origin("6104011242600068500").done();
    b.property("volume", 0x54b5cde27c2af597L).type(PrimitiveTypeId.INTEGER).origin("6104011242600068503").done();
    b.property("freq", 0x5b8f0dd215034d23L).type(PrimitiveTypeId.INTEGER).origin("6597507175067897123").done();
    b.aggregate("bins", 0x44617bd94982f23dL).target(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f15dL).optional(true).ordered(true).multiple(true).origin("4927355640491471421").done();
    b.alias("cp");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPlaylist() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("playlist", "Playlist", 0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f106L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:de050263-7aec-4e3f-a874-7935d74b9031(playlist.structure)/4927355640491471110");
    b.version(2);
    b.aggregate("songs", 0x44617bd94982f146L).target(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x54d1a88cacfa024eL).optional(false).ordered(true).multiple(true).origin("4927355640491471174").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSong() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("playlist", "Song", 0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f127L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:de050263-7aec-4e3f-a874-7935d74b9031(playlist.structure)/4927355640491471143");
    b.version(2);
    b.property("filepath", 0x44617bd94982f12aL).type(PrimitiveTypeId.STRING).origin("4927355640491471146").done();
    b.aggregate("timestamps", 0x44617bd94983cc98L).target(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f23aL).optional(false).ordered(true).multiple(true).origin("4927355640491527320").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSongRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("playlist", "SongRef", 0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x54d1a88cacfa024eL);
    b.class_(false, false, false);
    b.origin("r:de050263-7aec-4e3f-a874-7935d74b9031(playlist.structure)/6111851491469427278");
    b.version(2);
    b.associate("target", 0x54d1a88cacfa024fL).target(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f127L).optional(false).origin("6111851491469427279").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForVisualisation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("playlist", "Visualisation", 0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x4d5f699ec9c68c55L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:de050263-7aec-4e3f-a874-7935d74b9031(playlist.structure)/5575290994418945109");
    b.version(2);
    b.property("outputpath", 0x4d5f699ec9d125afL).type(PrimitiveTypeId.STRING).origin("5575290994419639727").done();
    b.aggregate("timestamps", 0x4d5f699ec9c68c76L).target(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f23aL).optional(false).ordered(true).multiple(true).origin("5575290994418945142").done();
    b.alias("Visualisation");
    return b.create();
  }
}
