package playlist.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Color_Constraints extends BaseConstraintsDescriptor {
  public Color_Constraints() {
    super(CONCEPTS.Color$Gd);
  }

  public static class R_Property extends BasePropertyConstraintsDescriptor {
    public R_Property(ConstraintsDescriptor container) {
      super(PROPS.r$9n6h, container);
    }
    @Override
    public boolean hasOwnValidator() {
      return true;
    }
    private static final SNodePointer validatePropertyBreakingPoint = new SNodePointer("r:fbac261e-7a0d-4960-b28a-5a86d5009e67(playlist.constraints)", "7381120681571984913");
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(validatePropertyBreakingPoint);
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      if ((propertyValue >= 0) && (propertyValue <= 255)) {
        return true;
      }
      return false;
    }
  }
  public static class G_Property extends BasePropertyConstraintsDescriptor {
    public G_Property(ConstraintsDescriptor container) {
      super(PROPS.g$bPeN, container);
    }
    @Override
    public boolean hasOwnValidator() {
      return true;
    }
    private static final SNodePointer validatePropertyBreakingPoint = new SNodePointer("r:fbac261e-7a0d-4960-b28a-5a86d5009e67(playlist.constraints)", "7381120681571993241");
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(validatePropertyBreakingPoint);
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      if ((propertyValue >= 0) && (propertyValue <= 255)) {
        return true;
      }
      return false;
    }
  }
  public static class B_Property extends BasePropertyConstraintsDescriptor {
    public B_Property(ConstraintsDescriptor container) {
      super(PROPS.b$bPVQ, container);
    }
    @Override
    public boolean hasOwnValidator() {
      return true;
    }
    private static final SNodePointer validatePropertyBreakingPoint = new SNodePointer("r:fbac261e-7a0d-4960-b28a-5a86d5009e67(playlist.constraints)", "7381120681571993467");
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(validatePropertyBreakingPoint);
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      if ((propertyValue >= 0) && (propertyValue <= 255)) {
        return true;
      }
      return false;
    }
  }
  public static class Alpha_Property extends BasePropertyConstraintsDescriptor {
    public Alpha_Property(ConstraintsDescriptor container) {
      super(PROPS.alpha$bQRU, container);
    }
    @Override
    public boolean hasOwnValidator() {
      return true;
    }
    private static final SNodePointer validatePropertyBreakingPoint = new SNodePointer("r:fbac261e-7a0d-4960-b28a-5a86d5009e67(playlist.constraints)", "7381120681571994221");
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(validatePropertyBreakingPoint);
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      if ((propertyValue >= 0) && (propertyValue <= 255)) {
        return true;
      }
      return false;
    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.r$9n6h, new R_Property(this));
    properties.put(PROPS.g$bPeN, new G_Property(this));
    properties.put(PROPS.b$bPVQ, new B_Property(this));
    properties.put(PROPS.alpha$bQRU, new Alpha_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Color$Gd = MetaAdapterFactory.getConcept(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f15eL, "playlist.structure.Color");
  }

  private static final class PROPS {
    /*package*/ static final SProperty r$9n6h = MetaAdapterFactory.getProperty(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f15eL, 0x44617bd94982f15fL, "r");
    /*package*/ static final SProperty g$bPeN = MetaAdapterFactory.getProperty(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f15eL, 0x44617bd94982f161L, "g");
    /*package*/ static final SProperty b$bPVQ = MetaAdapterFactory.getProperty(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f15eL, 0x44617bd94982f164L, "b");
    /*package*/ static final SProperty alpha$bQRU = MetaAdapterFactory.getProperty(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f15eL, 0x44617bd94982f168L, "alpha");
  }
}
