package playlist.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Color_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("RGBA(");
    tgs.append("" + SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.r$uJ20));
    tgs.append(", ");
    tgs.append("" + SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.g$uO8u));
    tgs.append(", ");
    tgs.append("" + SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.b$uO9V));
    tgs.append(", ");
    tgs.append("" + SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.alpha$uObR));
    tgs.append(")");
  }

  private static final class PROPS {
    /*package*/ static final SProperty r$uJ20 = MetaAdapterFactory.getProperty(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f15eL, 0x44617bd94982f15fL, "r");
    /*package*/ static final SProperty g$uO8u = MetaAdapterFactory.getProperty(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f15eL, 0x44617bd94982f161L, "g");
    /*package*/ static final SProperty b$uO9V = MetaAdapterFactory.getProperty(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f15eL, 0x44617bd94982f164L, "b");
    /*package*/ static final SProperty alpha$uObR = MetaAdapterFactory.getProperty(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f15eL, 0x44617bd94982f168L, "alpha");
  }
}
