package playlist.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Color_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("RGBA(");
    tgs.append("" + SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.r$9n6h));
    tgs.append(", ");
    tgs.append("" + SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.g$bPeN));
    tgs.append(", ");
    tgs.append("" + SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.b$bPVQ));
    tgs.append(", 255)");
  }

  private static final class PROPS {
    /*package*/ static final SProperty r$9n6h = MetaAdapterFactory.getProperty(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f15eL, 0x44617bd94982f15fL, "r");
    /*package*/ static final SProperty g$bPeN = MetaAdapterFactory.getProperty(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f15eL, 0x44617bd94982f161L, "g");
    /*package*/ static final SProperty b$bPVQ = MetaAdapterFactory.getProperty(0xe808b2f670da436eL, 0xbf6b14e1ed6cce5fL, 0x44617bd94982f15eL, 0x44617bd94982f164L, "b");
  }
}
