package playlist.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import playlist.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.Bin:
        return new Bin_TextGen();
      case LanguageConceptSwitch.Color:
        return new Color_TextGen();
      case LanguageConceptSwitch.Song:
        return new Song_TextGen();
      case LanguageConceptSwitch.Timestamp:
        return new Timestamp_TextGen();
    }
    return null;
  }

}
